services:
  httpet:
    image: ghcr.io/yaleman/httpet:latest
    ports:
      - "4200:9000"
    environment:
      - HTTPET_DATABASE_PATH=/db/httpet.sqlite
    volumes:
      - type: bind
        source: ./images
        target: /images
      - type: bind
        source: ./db/
        target: /db/
