services:
  httpet:
    image: ghcr.io/yaleman/httpet:latest
    ports:
      - "4200:9000"
    volumes:
      - type: bind
        source: ./images
        target: /images
      - type: bind
        source: ./httpet.sqlite
        target: /httpet.sqlite
